SNS/Controllers/OnBoardingController.cs
using AutoMapper;
using SNS.Models;
using SNS.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using SNS.Common;
using System.Web.Mvc;

namespace SNS.Controllers
{
    public class OnBoardingController : Controller
    {
        ApplicationDbContext db;
        public OnBoardingController()
        {
            db = new ApplicationDbContext();
        }
        // GET: Customers
        public ActionResult Index()
        {
            return View(db.Customers.ToList());
        }
        public ActionResult GetGridData()
        {
            return Json(new { Data = db.Customers.ToList() }, JsonRequestBehavior.AllowGet);
            // return Json(db.SalesAgent.ToList());
        }
        // GET: Customers/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customers exhibitor = db.Customers.Find(id);
            if (exhibitor == null)
            {
                return HttpNotFound();
            }
            return View(exhibitor);
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            Random rand = new Random((int)DateTime.Now.Ticks);

            string category = "";
            string username = "user" + rand.Next(1, 100);
            string password = "123456";
            if (Request.QueryString["Category"] != null)
            {
                category = Request.QueryString["Category"];
            }
            ViewBag.Category = category;
            ViewBag.Username = username;
            ViewBag.Password = password;

            CustomersVM dto = new CustomersVM();
            dto.Category = category;
            dto.Username = username;
            dto.Password = password;
            return View(dto);
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        // USC Code Generates here
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TheatreName,Address,Country,State,City,Zip,TheatreType,ScreenCount,TicketPrice,Email,Mobile,Category,Username,Password")] CustomersVM exhibitor)
        {
            Random rand = new Random();
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            try
            {
                if (ModelState.IsValid)
                {
                    var dmo = Mapper.Map<CustomersVM, Customers>(exhibitor);
                    dmo.CreatedOn = DateTime.Now;
                    dmo.UpdatedOn = DateTime.Now;
                    dmo.USC = Utility.GetThreeDigitCode(exhibitor.TheatreName) + "-" + Utility.GetThreeDigitCode(exhibitor.State) + "-" + Utility.GetThreeDigitCode(exhibitor.City) + "-" + exhibitor.Zip + "-" + rand.Next(1, 1000) + "S";
                    db.Customers.Add(dmo);
                    db.SaveChanges();
                    ExhibitorProfile1 expr1 = new ExhibitorProfile1();
                    expr1.USC = dmo.USC;
                    expr1.TheatreName = dmo.TheatreName;
                    expr1.Address = dmo.Address;
                    expr1.TheatreType = dmo.TheatreType;
                    expr1.ScreenCount = Convert.ToInt32(dmo.ScreenCount);
                    expr1.Email = dmo.Email;
                    expr1.ContactNumber = dmo.Mobile;
                    db.ExhibitorProfile1.Add(expr1);
                    db.SaveChanges();

                    string msgBody = "<p>We welcome you to Seats n Shows (SNS) a market place for cinema. <mark>Your Unique Screen Code or USC(<b>" + dmo.USC + "</b>) is an extremely important piece of  information for all your interactions with SNS.<mark></p>" +
                                            "<p>Please visit the following link and register.We would also like to advise you to complete your profile in order for us to better serve you.</p>" +
                                            "<br><p>Please contact us at help@sns.com for any questions of concerns</p>";
                    Utility.SendMail(msgBody, dmo.Email, "User Screen Code from S & S");
                    return this.RedirectToAction("AboutTheatre1", new { idQS = dmo.Id });
                }
            }
            catch (Exception ex)
            {
                return View();
            }
            return View(exhibitor);
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int id)
        {

            string category = "";
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Customers exhibitor = db.Customers.Find(id);
            var dmo = Mapper.Map<Customers, CustomersVM>(exhibitor);
            if (Request.QueryString["Category"] != null)
            {
                category = Request.QueryString["Category"];
            }
            ViewBag.Category = category;
            dmo.Category = category;
            if (dmo == null)
            {
                return HttpNotFound();
            }
            return View("Create", dmo);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,TheatreName,Address,Country,State,City,Zip,TheatreType,ScreenCount,TicketPrice,Email,Mobile")] CustomersVM exhibitor)
        {
            if (ModelState.IsValid)
            {
                var dmo = Mapper.Map<CustomersVM, Customers>(exhibitor);
                db.Entry(dmo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Customer", "Home");
            }
            return View(exhibitor);
        }

        // GET: Customers/Delete/5
        public ActionResult Delete()
        {
            int id = Convert.ToInt32(Request.QueryString["idQS"]);
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customers exhibitor = db.Customers.Find(id);
            if (exhibitor == null)
            {
                return HttpNotFound();
            }
            else
            {
                try { 
                db.Customers.Remove(exhibitor);
                db.SaveChanges();
                }catch(Exception ex)
                {
                    return View("Dashboard","Home");
                }
            }
            return RedirectToAction("Customer", "Home");
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Customers exhibitor = db.Customers.Find(id);
            db.Customers.Remove(exhibitor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AboutTheatre1()
        {
            ExhibitorProfile1 exPr1 = new ExhibitorProfile1();
            string txtUSC = Request.QueryString["usc"];
            if(txtUSC == null)
            {
                int idValue = Convert.ToInt32(Request.QueryString["idQS"]);
                txtUSC = db.Customers.Where(i => i.Id == idValue).Single().USC;
            }
            exPr1.USC = txtUSC;
            try
            {
                exPr1 = db.ExhibitorProfile1.Where(i => i.USC == txtUSC).Single();
                return View(exPr1);
            }
            catch (Exception ex)
            {
                exPr1.USC = txtUSC;
                return View(exPr1);
            }

            //exPr1VM.Id = exPr1.Id;
            //exPr1VM.TheatreName = exPr1.TheatreName;
            //return View(exPr1);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AboutTheatre1([Bind(Include = "Id,USC,TheatreName,Address,TheatreType,ScreenCount,StaffStrength,FandbBusiness,OtherAmenities,ContactNumber,Email,OwnershipProprietary,OwnershipPartnership,OwnershipCompany")] ExhibitorProfile1VM exPr1VM)
        {
            try
            {
                var errors = ModelState.Values.SelectMany(v => v.Errors);

                if (ModelState.IsValid)
                {
                    var dmo = Mapper.Map<ExhibitorProfile1VM, ExhibitorProfile1>(exPr1VM);
                    if (dmo.Id == 0)
                    {
                        db.ExhibitorProfile1.Add(dmo);
                    }
                    else
                    {
                        db.Entry(dmo).State = EntityState.Modified;
                    }
                    db.SaveChanges();
                    return this.RedirectToAction("AboutTheatre2", new { usc = dmo.USC });
                }
            }
            catch (Exception ex)
            {
                string errMsg = ex.Message;
                return View();
            }
            return View();
        }

        public ActionResult AboutTheatre2()
        {
            string uscValue = Request.QueryString["usc"];
            ExhibitorProfile2 exPr2 = new ExhibitorProfile2();

            string textUSC = uscValue;

            try
            {
                exPr2 = db.ExhibitorProfile2.Where(i => i.USC == textUSC).Single();
                return View("AboutTheatre2", exPr2);
            }
            catch (Exception ex)
            {
                exPr2.USC = textUSC;
                return View("AboutTheatre2", exPr2);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

SNS/Views/OnBoarding/AboutTheatre.cshtml
@model SNS.ViewModels.TheatreVM
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_LayoutOnBoarding.cshtml";
}
    <link rel="stylesheet" href="~/Content/resources/screen1/styles/form_basic.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<form class="form-basic" id="msform" method="post" action="sampleController.htm?action=about_theatres">
    <!-- progressbar -->
    <ul id="progressbar">
        <li class="active">
            <span class="fa-stack fa-2x">
                <i class="fa fa-circle fa-stack-2x icon-background1"></i><i class="fa fa-film fa-stack-1x" aria-hidden="true" style="font-size:30px;color:white;"></i>
            </span><br>
        </li>
        <li>
            <span class="fa-stack fa-2x">
                <i class="fa fa-circle fa-stack-2x icon-background1"></i><i class="fa fa-cubes fa-stack-1x" aria-hidden="true" style="font-size:30px;color:white;"></i>
            </span><br>
        </li>
        <li>
            <span class="fa-stack fa-2x">
                <i class="fa fa-circle fa-stack-2x icon-background1"></i><i class="fa fa-inr fa-stack-1x" aria-hidden="true" style="font-size:30px;color:white;"></i>
            </span><br>
        </li>
        <li>
            <span class="fa-stack fa-2x">
                <i class="fa fa-circle fa-stack-2x icon-background1"></i><i class="fa fa-cogs fa-stack-1x" aria-hidden="true" style="font-size:30px;color:white;"></i>
            </span><br>
        </li>
        <li>
            <span class="fa-stack fa-2x">
                <i class="fa fa-circle fa-stack-2x icon-background1"></i><i class="fa fa-eye fa-stack-1x" aria-hidden="true" style="font-size:30px;color:white;"></i>
            </span><br>
        </li>
        <li>
            <span class="fa-stack fa-2x">
                <i class="fa fa-circle fa-stack-2x icon-background1"></i><i class="fa fa-circle-o-notch fa-stack-1x" aria-hidden="true" style="font-size:30px;color:white;"></i>
            </span><br>
        </li>
    </ul>
    <div id="field_size" style="color:white">
        <fieldset>
            @using (Html.BeginForm("AboutTheatre1", "OnBoarding"))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.Partial("_PartialAboutTheatre", Model.AboutTheatreVM)
}
        </fieldset>        
        <fieldset>
            @Html.Partial("_PartialAboutInventory",Model.AboutInventoryVM)
        </fieldset>
        <fieldset>
            @Html.Partial("_PartialAboutRevenues",Model.AboutRevenuesVM)
        </fieldset>
        <fieldset>
            @Html.Partial("_PartialAboutTechnology",Model.AboutTechnologyVM)
        </fieldset>
        <fieldset>
          @Html.Partial("_PartialAboutLocalInsights",Model.AboutLocalInsightVM)
        </fieldset>
        <fieldset>
            @Html.Partial("_PartialAboutOtherThings",Model.AboutOtherThingsVM)
         </fieldset>
    </div>
</form>
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js'></script>
<script src="~/Content/resources/screen1/js/Processing.js"></script>

SNS/Views/OnBoarding/AboutTheatre1.cshtml
@model SNS.Models.ExhibitorProfile1
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_LayoutOnBoarding.cshtml";
}
<link rel="stylesheet" href="~/Content/resources/screen1/styles/form_basic.css">
<link href="~/Content/Customer/scripts/font-awesome.min.css" rel="stylesheet" />
<link href="~/Content/Customer/scripts/reset.min.css" rel="stylesheet" />

<!-- progressbar -->

<div id="" style="color:white">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <br /><br />
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <strong style="font-size:2em;">About Theatre</strong>
                <br /><br /><br />
                <h4>Theatre Name:</h4>
                @Html.EditorFor(model => model.TheatreName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TheatreName, "", new { @class = "text-danger" })

                <br />
                <h4>Address:</h4>
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                <br />

                <h4>Theatre Type:</h4>
                @Html.DropDownListFor(model => model.TheatreType,
                  new List<SelectListItem> {
new SelectListItem { Value = "Single" , Text = "Single" },
new SelectListItem { Value = "Multi" , Text = "Multi" }
                  },
                  new { @id = "ddSingleOrMulti", @class = "form-control", onchange = "chgSingleOrMulti" })

                @Html.ValidationMessageFor(model => model.TheatreType, "", new { @class = "text-danger" })
                <br />

                <h4>Screen Count:</h4>
                @Html.DropDownListFor(model => model.ScreenCount,
                              new List<SelectListItem> {
            new SelectListItem { Value = "1" , Text = "1" },
            new SelectListItem { Value = "2" , Text = "2" },
            new SelectListItem { Value = "3" , Text = "3" },
            new SelectListItem { Value = "4" , Text = "4" },
            new SelectListItem { Value = "5" , Text = "5" },
            new SelectListItem { Value = "6" , Text = "6" },
            new SelectListItem { Value = "7" , Text = "7" },
            new SelectListItem { Value = "8" , Text = "8" },
            new SelectListItem { Value = "9" , Text = "9" },
            new SelectListItem { Value = "10" , Text = "10" }
                  },
                  new { @id = "ddScreenCount", @class = "form-control", onchange = "SelectedIndexChanged()" })

                @Html.ValidationMessageFor(model => model.ScreenCount, "", new { @class = "text-danger" })
                <br />

                <h4>Staff Strength:</h4>
                @Html.DropDownListFor(model => model.StaffStrength,
                  new List<SelectListItem> {
new SelectListItem { Value = "1" , Text = "1" },
new SelectListItem { Value = "2" , Text = "2" },
new SelectListItem { Value = "3" , Text = "3" },
new SelectListItem { Value = "4" , Text = "4" },
new SelectListItem { Value = "5" , Text = "5" },
new SelectListItem { Value = "6" , Text = "6" },
new SelectListItem { Value = "7" , Text = "7" },
new SelectListItem { Value = "8" , Text = "8" },
new SelectListItem { Value = "9" , Text = "9" },
new SelectListItem { Value = "10" , Text = "10" }
                  },
                  new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StaffStrength, "", new { @class = "text-danger" })

                <br />

                <h4>F&amp;B Business:</h4>
                @Html.DropDownListFor(model => model.FandbBusiness,
                  new List<SelectListItem> {
new SelectListItem { Value = "Self-Owned" , Text = "Self-Owned" },
new SelectListItem { Value = "Out sourced" , Text = "Out sourced" },
new SelectListItem { Value = "Partnered" , Text = "Partnered" }
                  },
                  new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.FandbBusiness, "", new { @class = "text-danger" })
                <br />

                <h4>Other Amentities:</h4>
                @Html.EditorFor(model => model.OtherAmenities, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OtherAmenities, "", new { @class = "text-danger" })
                <br />

                <h4>Ownership</h4>
                <i>Proprietary</i>
                @Html.EditorFor(model => model.OwnershipProprietary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OwnershipProprietary, "", new { @class = "text-danger" })
                <i>Partnership</i>
                @Html.EditorFor(model => model.OwnershipPartnership, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OwnershipPartnership, "", new { @class = "text-danger" })
                <i>Company</i>
                @Html.EditorFor(model => model.OwnershipCompany, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OwnershipCompany, "", new { @class = "text-danger" })



                @*<div class="checkbox">
                        <label><input type="checkbox" id="chkProprietary" value="Proprietary">Proprietary</label>
                    </div>
                    <div class="checkbox">
                        <label><input type="checkbox" id="chkPartnership" value="Partnership">Partnership</label>
                    </div>
                    <div class="checkbox">
                        <label><input type="checkbox" id="chkCompany" value="Company">Company</label>
                    </div>*@

                <br />

                <h4>Contact Number:</h4>
                @Html.EditorFor(model => model.ContactNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactNumber, "", new { @class = "text-danger" })
                <br />

                <h4>Email:</h4>
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                <br />

                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.USC)
                <input type="submit" name="next" class="btn btn-primary" value="Save & Continue" />

                <a href="@Url.Action("Dashboard","Home")" class="btn btn-danger">Cancel</a>
                <br /><br />
            }
        </div>
        <div class="col-md-4"></div>
    </div>
</div>
<script src="~/Content/Customer/scripts/jquery.easing.min.js"></script>
<script src="~/Content/Customer/scripts/jquery.min.js"></script>

@*<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js'></script>*@
<script src="~/Content/resources/screen1/js/Processing.js"></script>

<script>

    function SelectedIndexChanged() {
        if ($('#ddScreenCount').val() == "1") {
            $('#ddSingleOrMulti').val("Single");
        }
        else {
            $('#ddSingleOrMulti').val("Multi");
        }
    }
    function chgSingleOrMulti() {
        if ($('#ddSingleOrMulti').val() == "Single") {
            $('#ddScreenCount').val("1");
        }
    }

</script>

SNS/Views/OnBoarding/AboutTheatre3.cshtml
@model SNS.Models.ExhibitorProfile3
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_LayoutOnBoarding.cshtml";
}
<link rel="stylesheet" href="~/Content/resources/screen1/styles/form_basic.css">
<link href="~/Content/Customer/scripts/reset.min.css" rel="stylesheet" />
<link href="~/Content/Customer/scripts/font-awesome.min.css" rel="stylesheet" />
@*<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">*@
@*<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">*@

<!-- progressbar -->

<div id="" style="color:white">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <br /><br />
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <strong style="font-size:2em;">Revenue Information</strong>
                <br /><br /><br />
                <h4>F&B Revenue:</h4>
                @Html.EditorFor(model => model.FandbRevenue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FandbRevenue, "", new { @class = "text-danger" })
                <br />
                <h4>Parking Revenue:</h4>
                @Html.EditorFor(model => model.ParkingRevenue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ParkingRevenue, "", new { @class = "text-danger" })
                <br />
                <h4>Local Advertising Revenue:</h4>
                @Html.EditorFor(model => model.LocalAdvertisingRevenue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LocalAdvertisingRevenue, "", new { @class = "text-danger" })
                <br />
                <h4>Other Revenue:</h4>
                @Html.EditorFor(model => model.OtherRevenue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OtherRevenue, "", new { @class = "text-danger" })
                <br />
                <h4>F&B Business:</h4>
                @Html.EditorFor(model => model.FandbBusiness, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FandbBusiness, "", new { @class = "text-danger" })
                <br />
                <h4>Additional Revenue:</h4>
                @Html.EditorFor(model => model.AdditionalRevenue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdditionalRevenue, "", new { @class = "text-danger" })
                <br />
                <h4>Effective Tax Rate:</h4>
                @Html.EditorFor(model => model.EffectiveTaxRate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EffectiveTaxRate, "", new { @class = "text-danger" })
                <br />
                <h4>Average Three Year Revenue:</h4>
                @Html.EditorFor(model => model.Avg3YrRevenue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Avg3YrRevenue, "", new { @class = "text-danger" })
                <br />
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.USC)

                <a href="@Url.Action("AboutTheatre2",new { usc = @Html.DisplayFor(model => model.USC) })" class="btn btn-primary">Back</a>
                <input type="submit" name="next" class="btn btn-success" value="Save & Continue" />
                <a href="@Url.Action("Dashboard","Home")" class="btn btn-danger">Cancel</a>

                <br /><br />
            }
        </div>
        <div class="col-md-4"></div>
    </div>
    }
</div>

<script src="~/Content/Customer/scripts/jquery.easing.min.js"></script>
<script src="~/Content/Customer/scripts/jquery.min.js"></script>

@*<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js'></script>*@
<script src="~/Content/resources/screen1/js/Processing.js"></script>

<script src="~/Content/resources/screen1/js/Processing.js"></script>

SNS/Views/OnBoarding/Delete.cshtml
@model SNS.Models.Customers

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutOnBoarding.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Exhibitor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TheatreName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TheatreName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TheatreType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TheatreType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ScreenCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ScreenCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TicketPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TicketPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedOn)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>